server:
  port: 8011

spring:
  datasource:
    url: jdbc:postgresql://125.64.98.21:5432/bldthingsboard
    username: postgres
    password: beilaidian
    driverClassName: org.postgresql.Driver
  #redis配置
  redis:
    host: 125.64.98.21
    port: 6366
    password: bld67397791517
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        #连接池中最大的空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间（毫秒）
    timeout: 1000

#mybatis 配置
mybatis:
  type-aliases-package: com.cqbld.po
  mapper-locations: classpath:mybatis/mapper/*.xml
