server:
  port: 8082

spring:
#  datasource:
#    url: jdbc:postgresql://125.64.98.21:5432/bldthingsboard
#    username: postgres
#    password: beilaidian
#    driverClassName: org.postgresql.Driver
#    url: jdbc:mysql://125.64.98.21:3307/bldProcess?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: lyx
#    password: abc7178377
#    driverClassName: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  #redis配置
  redis:
    host: 125.64.98.21
    port: 6366
    password: bld67397791517
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1
        #连接池中最大的空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
        #连接超时时间（毫秒）
    timeout: 1000

#mybatis 配置

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cqbld.**.po, com.cqbld.**.entity,
